function dCoM_to_Point = calcDistFrom_CoM(in1,in2)
%calcDistFrom_CoM
%    dCoM_to_Point = calcDistFrom_CoM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    06-Apr-2023 10:52:15

p1 = in2(1,:);
p2 = in2(2,:);
z1 = in1(1,:);
z3 = in1(3,:);
dCoM_to_Point = sqrt(abs(-p1+z1./8.0+sin(z3).*(3.39e+2./1.0e+3)).^2+abs(-p2+cos(z3).*(3.39e+2./1.0e+3)+1.0./8.0).^2);
