function d_dCoM_to_Point_dz = calcDistFrom_CoM_jacobian(in1,in2)
%calcDistFrom_CoM_jacobian
%    d_dCoM_to_Point_dz = calcDistFrom_CoM_jacobian(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    06-Apr-2023 10:52:16

p1 = in2(1,:);
p2 = in2(2,:);
z1 = in1(1,:);
z3 = in1(3,:);
t2 = cos(z3);
t3 = sin(z3);
t4 = -p1;
t5 = -p2;
t6 = z1./8.0;
t7 = t2.*(3.39e+2./1.0e+3);
t8 = t3.*(3.39e+2./1.0e+3);
t9 = t5+t7+1.0./8.0;
t11 = t4+t6+t8;
t10 = abs(t9);
t13 = abs(t11);
t14 = sign(t11);
t12 = t10.^2;
t15 = t13.^2;
t16 = t12+t15;
t17 = 1.0./sqrt(t16);
d_dCoM_to_Point_dz = [(t13.*t14.*t17)./8.0,0.0,t17.*(t3.*t10.*sign(t9).*(3.39e+2./5.0e+2)-t2.*t13.*t14.*(3.39e+2./5.0e+2)).*(-1.0./2.0),0.0];
