function M = M(in1,t)
%M
%    M = M(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    27-Mar-2023 10:21:10

thetax_ = in1(2,:);
t2 = cos(thetax_);
t3 = t2.*4.59225e-1;
t4 = t3-1.515972222222222e-2;
M = reshape([2.605493055555556e-1,t4,t4,5.942384588888889],[2,2]);
