function Ta_subsd = Ta(dphix_,dthetax_,thetax_,phix_,t)
%Ta
%    Ta_subsd = Ta(DPHIX_,DTHETAX_,THETAX_,PHIX_,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Mar-2023 09:03:36

Ta_subsd = dphix_.^2.*(2.3e+1./3.2e+2)+dthetax_.^2.*2.9086366+dphix_.*dthetax_.*cos(thetax_).*3.8985e-1;
