function Tk_subsd = Tk(dphix_,dthetax_,thetax_,phix_,t)
%Tk
%    Tk_subsd = Tk(DPHIX_,DTHETAX_,THETAX_,PHIX_,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    27-Mar-2023 10:21:11

Tk_subsd = dphix_.^2.*2.9840625e-2;
