function Tw_subsd = Tw(dphix_,dthetax_,thetax_,phix_,t)
%Tw
%    Tw_subsd = Tw(DPHIX_,DTHETAX_,THETAX_,PHIX_,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Mar-2023 16:53:03

Tw_subsd = (dphix_.*(2.5e+1./1.2e+1)-dthetax_.*(3.7e+1./1.2e+1)).^2.*1.18e-3+dphix_.^2.*(3.0./1.28e+2)+dthetax_.^2.*5.13375e-2+dphix_.*dthetax_.*cos(thetax_).*6.9375e-2;
