function Va_subsd = Va(dphix_,dthetax_,thetax_,phix_,t)
%Va
%    Va_subsd = Va(DPHIX_,DTHETAX_,THETAX_,PHIX_,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    27-Mar-2023 10:21:11

Va_subsd = cos(thetax_).*3.0595428e+1;
