function Vw_subsd = Vw(dphix_,dthetax_,thetax_,phix_,t)
%Vw
%    Vw_subsd = Vw(DPHIX_,DTHETAX_,THETAX_,PHIX_,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    27-Mar-2023 10:21:11

Vw_subsd = cos(thetax_).*5.44455;
