function b = b_func(in1,in2)
%B_FUNC
%    B = B_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    31-Mar-2023 07:17:15

uLim1 = in2(:,1);
uLim2 = in2(:,2);
zLim1_1 = in1(1);
zLim1_2 = in1(5);
zLim2_1 = in1(2);
zLim2_2 = in1(6);
zLim3_1 = in1(3);
zLim3_2 = in1(7);
zLim4_1 = in1(4);
zLim4_2 = in1(8);
t2 = -uLim1;
t3 = -zLim1_1;
t4 = -zLim2_1;
t5 = -zLim3_1;
t6 = -zLim4_1;
mt1 = [t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6];
mt2 = [t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;t3;t4;t5;t6;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2];
mt3 = [zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;zLim1_2;zLim2_2;zLim3_2;zLim4_2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;t2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2];
mt4 = [uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2;uLim2];
b = [mt1;mt2;mt3;mt4];
