function out1 = extract_uN_from_DV(in1)
%extract_uN_from_DV
%    OUT1 = extract_uN_from_DV(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    07-Apr-2023 08:38:09

uN1 = in1(1,:);
uN2 = in1(2,:);
uN3 = in1(3,:);
uN4 = in1(4,:);
uN5 = in1(5,:);
uN6 = in1(6,:);
uN7 = in1(7,:);
uN8 = in1(8,:);
uN9 = in1(9,:);
uN10 = in1(10,:);
uN11 = in1(11,:);
uN12 = in1(12,:);
uN13 = in1(13,:);
uN14 = in1(14,:);
uN15 = in1(15,:);
uN16 = in1(16,:);
uN17 = in1(17,:);
uN18 = in1(18,:);
uN19 = in1(19,:);
uN20 = in1(20,:);
uN21 = in1(21,:);
uN22 = in1(22,:);
uN23 = in1(23,:);
uN24 = in1(24,:);
uN25 = in1(25,:);
uN26 = in1(26,:);
out1 = [uN1;uN2;uN3;uN4;uN5;uN6;uN7;uN8;uN9;uN10;uN11;uN12;uN13;uN14;uN15;uN16;uN17;uN18;uN19;uN20;uN21;uN22;uN23;uN24;uN25;uN26];
