function out1 = get_N_decisionVars
%get_N_decisionVars
%    OUT1 = get_N_decisionVars

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    06-Apr-2023 14:29:14

out1 = 3.05e+2;
