function out1 = get_N_decisionVars
%get_N_decisionVars
%    OUT1 = get_N_decisionVars

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Apr-2023 09:23:06

out1 = 2.59e+2;
