function out1 = get_N_decisionVars
%get_N_decisionVars
%    OUT1 = get_N_decisionVars

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Apr-2023 16:59:57

out1 = 2.55e+2;
end
