function out1 = getNumPtsForGeneratedCode
%getNumPtsForGeneratedCode
%    OUT1 = getNumPtsForGeneratedCode

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    29-Mar-2023 08:32:01

out1 = 5.1e+1;
