function out1 = getNumPtsForGeneratedCode
%getNumPtsForGeneratedCode
%    OUT1 = getNumPtsForGeneratedCode

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Apr-2023 09:21:55

out1 = 5.1e+1;
